- job-template:
    name: 'devstudio.product_{devstudio-stream}'
    disabled: '{obj:disabled}'
    description: |
      Tycho-based build of JBDS update site, monitoring Github for changes.

      <p><i>Build should take ~ 40min.</i>
      <h2><a style="color:#FF9933" href="http://download.jboss.org/jbosstools/builds/cascade/">Build Job Cascade & Results</a></h2>

      <p>See also:
        <ul><li><a href=/hudson/view/EAP-CI/view/EAP6-CI/>EAP 6 jobs</a>
        <li><a href=http://download.devel.redhat.com/released/JBEAP-6/>EAP 6.x releases</a> (internal)
        <li><a href=http://www.jboss.org/jbossas/downloads>EAP 6.x releases</a> (public)
      </ul>
    node: "{nodes}"
    logrotate:
      daysToKeep: 10
      numToKeep: 10
      artifactDaysToKeep: 10
      artifactNumToKeep: 10
    properties:          
      - github:
          url: https://github.com/jbdevstudio/jbdevstudio-product
    parameters:
      - string:
          name: MAVEN_FLAGS
          default: "{ci-maven-flags} -P hudson,eap,unified.target"
          description: "{maven-flags-description}"
      - choice:
          name: update.site.description
          choices:
            - Nightly Build
            - Development Milestone
            - Stable Release
      - string:
          name: jbosstools_site_stream
          default: master
      - string:
          name: TARGET_PLATFORM_VERSION
          default: "{target-platform-version}"
          description: "Target platform used for building/compilation"
      - string:
          name: TARGET_PLATFORM_VERSION_MAXIMUM
          default: "{target-platform-version-maximum}"
          description: "Target platform used for testing"
      - string:
          name: JBOSS_CENTRAL_ZIP
          description: "This should be overwritten by the value passed in from upstream job jbosstools-centraltarget_*"
          default: https://devstudio.redhat.com/9.0/snapshots/builds/jbosstools-build-sites.aggregate.central-site_${{jbosstools_site_stream}}/latest/all/repository.zip
      - bool:
          name: skipRevisionCheckWhenPublishing
          default: false
          description: |
            Check box to always publish new build to staging / nightly. <br/>
            Unchecked, this job will check previous build's revision to decide if this build needs <br/>
            to overwrite the previous one, or if it's in fact the same source & therefore same binaries.
    scm:
      - git:
          url: git@github.com:jbdevstudio/jbdevstudio-product.git
          branches: 
            - '{default-remote}/{branch}'
          browser: githubweb
          browser-url: https://github.com/jbdevstudio/jbdevstudio-product/
          basedir: "sources/product"
          wipe-workspace: false
    jdk: '{default-jdk}'

    triggers:
      - pollscm: "{scm-schedule}"    

    builders:
      - shell: |
               if  [[ ! -d jbds-build-env ]]; then
               ln -s /home/hudson/static_build_env/jbds jbds-build-env
               fi
      - maven-target:
          goals: "clean install ${{MAVEN_FLAGS}} -DTARGET_PLATFORM_VERSION=${{TARGET_PLATFORM_VERSION_MAXIMUM}} -Ppack200"
          maven-version: maven-3.2.5
          private-repository: true
          java-opts: 
            - "{jvm-memory}"
          properties: 
            - JOB_NAME=${{JOB_NAME}}
            - BUILD_ID=${{BUILD_ID}}
            - BUILD_NUMBER=${{BUILD_NUMBER}}
            - maven.test.failure.ignore=true
            - maven.test.error.ignore=true
            - download.cache.directory={download-cache}
            - targetPlatformGroup=jbdevstudio
            - jbosstools-site=http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-build-sites.aggregate.site_${{jbosstools_site_stream}}/latest/all/repo/
          pom: ${{WORKSPACE}}/sources/product/pom.xml
      - shell: |
               # move the update site target folder temporarily
               rm -fr ${{WORKSPACE}}/tmp-target
               mv ${{WORKSPACE}}/sources/product/site/target ${{WORKSPACE}}/tmp-target
               
               # now rebuild the update site, without pack200
      - maven-target:
          goals: "clean install ${{MAVEN_FLAGS}} -DTARGET_PLATFORM_VERSION=${{TARGET_PLATFORM_VERSION_MAXIMUM}}"
          maven-version: maven-3.2.5
          private-repository: true
          java-opts: 
            - "{jvm-memory}"
          properties: 
            - JOB_NAME=${{JOB_NAME}}
            - BUILD_ID=${{BUILD_ID}}
            - BUILD_NUMBER=${{BUILD_NUMBER}}
            - maven.test.failure.ignore=true
            - maven.test.error.ignore=true
            - download.cache.directory={download-cache}
            - targetPlatformGroup=jbdevstudio
            - jbosstools-site=http://download.jboss.org/jbosstools/mars/snapshots/builds/jbosstools-build-sites.aggregate.site_${{jbosstools_site_stream}}/latest/all/repo/
          pom: ${{WORKSPACE}}/sources/product/site/pom.xml          
      - maven-target:
          goals: "-U org.apache.maven.plugins:maven-dependency-plugin:2.9:unpack"
          maven-version: maven-3.2.5
          private-repository: false
          properties:
            - artifact=org.jboss.tools.releng:jbosstools-releng-publish:4.3.0.CR1-SNAPSHOT:zip
            - outputDirectory=${{WORKSPACE}}/sources
            - trimVersion=true
            - mdep.stripClassifier=true
            - mdep.stripVersion=true
      - shell: |
               # replace the update-core zip + sha256 with the non-pack200 versions
               mv -f ${{WORKSPACE}}/sources/product/site/target/com.jboss.devstudio.core.site-*.zip* ${{WORKSPACE}}/tmp-target/
               # purge the target folder built w/o pack200
               rm -fr ${{WORKSPACE}}/sources/product/site/target
               # move the temporary folder back to where it should be
               mv ${{WORKSPACE}}/tmp-target ${{WORKSPACE}}/sources/product/site/target

               ###############################################

               if [[ ${{skipRevisionCheckWhenPublishing}} == "true" ]] || [[ $(. ${{WORKSPACE}}/sources/util/checkLatestPublishedSHA.sh -s ${{WORKSPACE}}/sources/product/site/target/repository -t http://www.qa.jboss.com/binaries/RHDS/9.0/snapshots/builds/${{JOB_NAME}}/latest/all/repo/) == "true" ]]; then
                 cd ${{WORKSPACE}}/sources/product/results
                 M2_HOME=/qa/tools/opt/apache-maven-3.2.5/
                 $M2_HOME/bin/mvn deploy -U -e -Pdeploy-to-jboss.org -Dmaven.repo.local=$WORKSPACE/.repository -Djbosstools_site_stream=${{jbosstools_site_stream}} ${{MAVEN_FLAGS}}
               else
                 echo "Publish cancelled (nothing to do). Skip this check with skipRevisionCheckWhenPublishing=true"
                 BUILD_DESCRIPTION="NOT PUBLISHED: UNCHANGED"
               fi

    publishers:
        - description-setter: 
            regexp: "BUILD_DESCRIPTION='(.+)'"
            description: "\\1"
        - raw:
            xml: |
              <hudson.plugins.downstream__ext.DownstreamTrigger><childProjects>jbosstools-discovery_{stream}, devstudio.versionwatch_{devstudio-stream}</childProjects><threshold><name>UNSTABLE</name><ordinal>1</ordinal><color>YELLOW</color><completeBuild>true</completeBuild></threshold><thresholdStrategy>AND_HIGHER</thresholdStrategy><onlyIfSCMChanges>false</onlyIfSCMChanges><onlyIfLocalSCMChanges>false</onlyIfLocalSCMChanges></hudson.plugins.downstream__ext.DownstreamTrigger>
        - email:
            recipients: "jboss-devstudio-builds-list@redhat.com nboldt@redhat.com mistria@redhat.com"
            send-to-individuals: true
            notify-every-unstable-build: true
        - build-publisher:
            name: ""
            publish-unstable-builds: true
            publish-failed-builds: false

    wrappers: 
        - raw:
            xml: |
               <hudson.plugins.build__timeout.BuildTimeoutWrapper><strategy class="hudson.plugins.build_timeout.impl.AbsoluteTimeOutStrategy"><timeoutMinutes>180</timeoutMinutes></strategy><operationList><hudson.plugins.build__timeout.operations.AbortOperation/></operationList></hudson.plugins.build__timeout.BuildTimeoutWrapper>
