BuildChow
=========

BuildChow is the nickname for templates of JBoss Tools and Developer
Studio Jenkins jobs.

By using templates we do not have to rely on Jenkins UI to manually update jobs
or bulk-update in large set of config.xml files.

BuildChow uses http://ci.openstack.org/jenkins-job-builder[Jenkins Job
Builder](jjb) from Openstack.org.

== Requirements

. Python 2.7+
. Python PIP
. Git

On Fedora you get this by runing: `yum install -y python-pip git`

== How to use

=== Installation

First need to install jjb.

For now we use a custom fork since not all patches applied yet.

As root, run this:

```
$ pip install git+https://github.com/maxandersen/jenkins-job-builder@jbosstools
```

Once installed you can run the following to generate jobs into a folder named `generated`.

=== Running jjb

INFO: Please note that for supporting Jenkins host specific overrides you *must* change the directory
to where the .ini file is and mention the .ini file to run it correctly.

```
$ cd configs/default
$ jenkins-jobs --conf jenkins_jobs.ini test ../../templates/ -o generated
```

This will generate 40+ jobs into the `generated` folder.

=== Producing config.xml files

If you would like to see these config files as JOB_NAME/config.xml files instead, you can run this:

```
./etc/todirformat.sh configs/default/generated master
```

This will generate 40+ config.xml into the `generated-old` folder.

=== Uploading config changes to Jenkins

To upload directly to Jenkins you need to create a copy of `jobs_jenkins.ini` with your own username/password. Make sure you do *not* commit it!

Then run the following:

```
$ cd configs/default
$ jenkins-jobs --conf jenkins_jobs_mypassword.ini update ../../templates/ 
```

== Layout

|===
|Name | Description

| link:templates[]
| The templates for jobs written in `.yaml`. If you want to add or change a job then you tend to edit this.

| link:configs[]
| Directory with a directory per specific Jenkins host.

| link:configs/default[]
| Has the default Jenkins setup (currently using internal JBoss Jenkins). Has `.inc` files to define defaults
  for machine specific settings. Intent is that other configs can use this as a fallback.

| link:configs/dockerhost[]
| Example for custom ini file using dockerhost + override of machine specific includes.

| link:etc/todirformat.sh[]
| Script to convert the flat names used by `jjb` to the "view" format used by old Jenkins config.xml backups

| link:todo.adoc[]
| Todo items/remaining questions regarding the templates. One day it should be empty and then removed.


