## map from descriptive name to list of JBIDE and/or JBDS components in JIRA.
JIRA_components = {
    "Aerogear          ": { "aerogear-hybrid", "cordovasim" },
    "Arquillian        ": { "arquillian" },
    # "Error Reporting " : {"aeri"},
    "Base              ": { "common", "foundation", "usage" },
    # "Batch           ": { "batch"},
    "BrowserSim        ": { "browsersim" },
    "build, ci, maven-plugins": { "build" },
    "build-sites       ": { "updatesite" },
    "Central           ": { "central", "maven", "project-examples" },
    # "CDI             " : { "cdi"},
    "Discovery         ": { "central-update" },
    # "Docker          ": { "docker" },
    "dl.j.o, devdoc    ": { "website" },
    # "Easymport       ": { "easymport" },
    "Forge             ": { "forge" },
    "Freemarker        ": { "freemarker" },
    "Hibernate         ": { "hibernate"},
    "Integration-Tests ": { "qa" },
    "JavaEE            ": { "jsf", "seam2", "cdi", "cdi-extensions", "jsp/jsf/xml/html-source-editing"},
    # "javascript      ": { "javascript", "nodejs"},
    "JST               ": { "jst"},
    "LiveReload        ": { "livereload" },
    # "Maven           ": { "maven"},
    "OpenShift         ": { "openshift", "cdk" },
    # "Project Examples": { "project-examples"},
    "Server            " : {  "server", "archives", "jmx" },
    # "Usage Analytics " : { "usage"},
    "versionwatch      ": { "versionwatch" },
    "VPE               ": { "visual-page-editor-core", "visual-page-editor-templates"},
    "Webservices       ": { "webservices"}
    }

# there are more N&N pages than there are JIRA components (eg., jbosstools-central includes Central, Maven and Project Examples) so this list is a bit different from teh above one
NN_components = {
    "Aerogear          ": { "aerogear-hybrid", "cordovasim" },
    "Arquillian        ": { "arquillian" },
    "Error Reporting   " : {"aeri"},
    "Base              ": { "common", "foundation", "usage" },
    "Batch             ": { "batch"},
    "BrowserSim        ": { "browsersim" },
    # "build, ci, maven-plugins": { "build" },
    # "build-sites     ": { "updatesite" },
    "Central           ": { "central", "maven", "project-examples" },
    "CDI               ": { "cdi"},
    # "Discovery       ": { "central-update" },
    "Docker            ": { "docker" },
    # "dl.j.o, devdoc  ": { "website" },
    "Easymport         ": { "easymport" },
    "Forge             ": { "forge"},
    "Freemarker        ": {"freemarker"},
    "Hibernate         ": { "hibernate"},
    # "Integration-Tests": { "qa" },
    # "JavaEE          ": { "jsf", "seam2", "cdi", "cdi-extensions" },
    "Javascript        ": { "javascript", "nodejs"},
    "JSF               ": { "jsp/jsf/xml/html-source-editing", "jsf"},
    "JST               ": { "jst"},
    "LiveReload        ": { "livereload" },
    "Maven             ": { "maven"},
    "OpenShift         ": { "openshift", "cdk" },
    "Project Examples  ": { "project-examples"},
    "Server            " : {  "server", "archives", "jmx" },
    "Usage Analytics   " : { "usage"},
    # "versionwatch    ": { "versionwatch" },
    "Visual Editor     ": { "visual-page-editor-core", "visual-page-editor-templates"},
    "Webservices / Rest": { "webservices"}
    }